#!/bin/bash
# Start all AIME-2.0 services

echo "🚀 Starting AIME-2.0 Services"
echo "============================="
echo ""
echo "This will start 4 services. Use separate terminal windows for each."
echo ""
echo "Terminal 1: Express Backend (port 3001)"
echo "Terminal 2: Python FastAPI Backend (port 8000)"
echo "Terminal 3: PuttSolver Service (port 8081)"
echo "Terminal 4: Frontend (port 3000)"
echo ""
echo "Commands to run:"
echo ""
echo "Terminal 1:"
echo "  cd $(pwd)"
echo "  npm run server:dev"
echo ""
echo "Terminal 2:"
echo "  cd $(pwd)/backend"
echo "  source venv/bin/activate"
echo "  uvicorn main:app --reload --port 8000"
echo ""
echo "Terminal 3:"
echo "  cd $(pwd)/putt-solver-service"
echo "  source venv/bin/activate"
echo "  export PUTTSOLVER_MODE=mock"
echo "  uvicorn main:app --host 0.0.0.0 --port 8081 --reload"
echo ""
echo "Terminal 4:"
echo "  cd $(pwd)"
echo "  npm start"
echo ""
