import React, { useState } from 'react';
import { Session } from '../../types';
import './SessionDuplicator.css';

interface SessionDuplicatorProps {
  session: Session;
  onDuplicate: (duplicatedSession: Partial<Session>) => void;
  onClose: () => void;
}

const SessionDuplicator: React.FC<SessionDuplicatorProps> = ({ session, onDuplicate, onClose }) => {
  const [modifications, setModifications] = useState({
    title: session.title.replace(/session/gi, 'Session').replace(/work/gi, 'Work'),
    summary: session.summary,
    nextSteps: session.nextSteps,
    filesModified: session.filesModified,
    blockers: session.blockers,
    keyDecisions: session.keyDecisions,
    challenges: session.challenges,
    solutions: session.solutions,
    codeChanges: session.codeChanges,
    outcomes: session.outcomes,
    learnings: session.learnings,
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setModifications(prev => ({ ...prev, [name]: value }));
  };

  const handleDuplicate = () => {
    const duplicatedSession: Partial<Session> = {
      ...session,
      id: '', // Will be generated by backend
      title: modifications.title,
      date: new Date().toISOString().split('T')[0], // Today's date
      status: 'In Progress',
      summary: modifications.summary,
      nextSteps: modifications.nextSteps,
      filesModified: modifications.filesModified,
      blockers: modifications.blockers,
      keyDecisions: modifications.keyDecisions,
      challenges: modifications.challenges,
      solutions: modifications.solutions,
      codeChanges: modifications.codeChanges,
      outcomes: modifications.outcomes,
      learnings: modifications.learnings,
    };

    onDuplicate(duplicatedSession);
    onClose();
  };

  return (
    <div className="session-duplicator-overlay">
      <div className="session-duplicator-modal">
        <div className="session-duplicator-header">
          <h2>📋 Duplicate Session</h2>
          <button className="close-button" onClick={onClose}>
            ×
          </button>
        </div>

        <div className="session-duplicator-content">
          <div className="original-session-info">
            <h3>Original Session</h3>
            <div className="session-preview">
              <strong>{session.title}</strong>
              <p className="session-date">{session.date}</p>
              {session.summary && (
                <p className="session-summary">{session.summary.substring(0, 100)}...</p>
              )}
            </div>
          </div>

          <div className="modifications-section">
            <h3>Modify for New Session</h3>

            <div className="form-group">
              <label htmlFor="title">Session Title *</label>
              <input
                type="text"
                id="title"
                name="title"
                value={modifications.title}
                onChange={handleInputChange}
                required
              />
            </div>

            <div className="form-group">
              <label htmlFor="summary">Summary</label>
              <textarea
                id="summary"
                name="summary"
                value={modifications.summary}
                onChange={handleInputChange}
                rows={3}
                placeholder="What will you work on in this session?"
              />
            </div>

            <div className="form-group">
              <label htmlFor="nextSteps">Next Steps</label>
              <textarea
                id="nextSteps"
                name="nextSteps"
                value={modifications.nextSteps}
                onChange={handleInputChange}
                rows={2}
                placeholder="What are the next steps for this session?"
              />
            </div>

            <div className="form-group">
              <label htmlFor="filesModified">Files to Modify</label>
              <textarea
                id="filesModified"
                name="filesModified"
                value={modifications.filesModified}
                onChange={handleInputChange}
                rows={2}
                placeholder="Which files will you be working on?"
              />
            </div>

            <div className="form-group">
              <label htmlFor="blockers">Potential Blockers</label>
              <textarea
                id="blockers"
                name="blockers"
                value={modifications.blockers}
                onChange={handleInputChange}
                rows={2}
                placeholder="Any potential blockers or challenges?"
              />
            </div>
          </div>
        </div>

        <div className="session-duplicator-footer">
          <button className="btn-secondary" onClick={onClose}>
            Cancel
          </button>
          <button className="btn-primary" onClick={handleDuplicate}>
            📋 Duplicate Session
          </button>
        </div>
      </div>
    </div>
  );
};

export default SessionDuplicator;
